version: '3.8'

services:
    backend:
        container_name: backend-game
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes: 
            - .:/app
            - /app/node_modules
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - REDIS_URL=${REDIS_URL}
        depends_on:
            - db
            - redis
        networks:
            - backend-network

    db:
        container_name: db-game
        image: postgres:16
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5431:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - backend-network

    redis:
        container_name: redis-game
        image: redis:7
        ports:
            - '6380:6379'
        networks:
            - backend-network
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - '8080:80'
        environment:
           PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
           PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        networks:
            - backend-network

volumes:
    postgres-data:

networks:
    backend-network:
